events {}

http {

    server {
        listen 80;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;

        ssl_certificate /etc/nginx/certs/servidor.crt;
        ssl_certificate_key /etc/nginx/certs/servidor.key;

        location / {
            return 200 "SWARM HTTPS OK\n";
        }
    }
}